// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GRPCServicesClient is the client API for GRPCServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCServicesClient interface {
	Call(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
}

type gRPCServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCServicesClient(cc grpc.ClientConnInterface) GRPCServicesClient {
	return &gRPCServicesClient{cc}
}

func (c *gRPCServicesClient) Call(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	out := new(RPCResponse)
	err := c.cc.Invoke(ctx, "/proto.GRPCServices/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCServicesServer is the server API for GRPCServices service.
// All implementations must embed UnimplementedGRPCServicesServer
// for forward compatibility
type GRPCServicesServer interface {
	Call(context.Context, *RPCRequest) (*RPCResponse, error)
	mustEmbedUnimplementedGRPCServicesServer()
}

// UnimplementedGRPCServicesServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCServicesServer struct {
}

func (*UnimplementedGRPCServicesServer) Call(context.Context, *RPCRequest) (*RPCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedGRPCServicesServer) mustEmbedUnimplementedGRPCServicesServer() {}

func RegisterGRPCServicesServer(s *grpc.Server, srv GRPCServicesServer) {
	s.RegisterService(&_GRPCServices_serviceDesc, srv)
}

func _GRPCServices_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServicesServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GRPCServices/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServicesServer).Call(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GRPCServices",
	HandlerType: (*GRPCServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GRPCServices_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/app.proto",
}
