
[RPCname]
aut="localhost:9877"
dash="localhost:9878"
shop="localhost:9879"
prod="localhost:9880"
news="localhost:9881"
tmpl="localhost:9882"
page="localhost:9883"
ord="localhost:9884"
camp="localhost:9885"
shipper="localhost:9886"
cus="localhost:9887"
rep="localhost:9888"
part="localhost:9889"
ware="localhost:9890"
invc="localhost:9891"
rsrc="localhost:9892"
[dbsession]
h="127.0.0.1:27017"
d="cuahang"
u="cuahang"
p="cuahang1234@"
[config]
domainallow="b.localhost,http://localhost.com,http://duyhf.noip.me,http://localhost:8080"
hostname="http://localhost.com"
sameurllimit=10
requestlimit=500  
